language: python
python:
    - "3.5"
install:
    - "pip install -e .[test]"
script:
    - "flake8 ."
    - "which blog"
    - "python -c 'from danube_delta.config.development import *'"
    - "python -c 'from danube_delta.config.production import *'"
    - "python -c 'from danube_delta import plugins'"
sudo: false
